### ISSUE TITLE
Undocumented naming requirement for surfaces

### ISSUE THREAD

**Issue by MakisH** [precice/calculix-adapter#100]
As @FWey noticed, it looks like surfaces defined in the CalculiX adapter need to start with an `S`. One example is our heat-exchanger tutorial (here `Sinner-interface`, in the file `inner-interface.sur`):

```
** Surfaces based on inner-interface
*SURFACE, NAME=Sinner-interface
```

@boris-martin @KyleDavisSA any idea where this requirement originates from? I could not find something in Lucia's thesis, nor in the [adapter config docs](https://precice.org/adapter-calculix-config.html). Apparently, this is not a requirement for CalculiX itself.

If we cannot drop this requirement, we should at least document it.

**Comment by boris-martin** [comment]
It's already fixed in https://github.com/precice/precice.github.io/pull/180 :)

It seems to come from this:

https://github.com/precice/calculix-adapter/blob/4496e8f160ec121481653baf44ec032813409ac6/adapter/CCXHelpers.c#L14-L28

I guess changing it would be a backward compatibility nightmare. No idea who did that nor why.
