### ISSUE TITLE
Using a higher order finite element mesh is problematic

### ISSUE THREAD

**Issue by IshaanDesai** [precice/calculix-adapter#55]
If the adapter is run with a case setup having higher order mesh elements, the higher order nodes get detected as physical nodes while defining the coupling boundary. For example consider the following mesh:

![Screenshot from 2021-03-17 10-51-18](https://user-images.githubusercontent.com/44898158/111460821-b6c30400-871c-11eb-8e23-d9cd6a83fc91.png)

Here there are only four nodes along the Y axis. But if the mesh element type `he20`:
![Screenshot from 2021-03-17 12-32-32](https://user-images.githubusercontent.com/44898158/111460931-e2de8500-871c-11eb-940e-a9d40a8905c6.png)
is defined, then the coupling boundary shows seven nodes along the Y axis. This means that in addition to the four physical nodes, additional three higher order nodes are also detected. 

This is problematic and needs to be resolved by having some sort of filtering in the adapter. A similar situation arises while extracting nodes from a FEniCS mesh, and the FEniCS-Adapter handles the filtering [here](https://github.com/precice/fenics-adapter/blob/be1b49de1adb3fef61b496ee84cd0183fed6a335/fenicsprecice/adapter_core.py#L230-L251).

**Comment by IshaanDesai** [comment]
In case someone is interested in how a higher order element mesh can be generated for the perpendicular flap geometry case: https://calculix.discourse.group/t/two-types-of-elements-in-a-cgx-mesh/483/3

**Comment by UlrichHeck** [comment]
We have carried out some further tests with different FE codes (e.g. Abaqus) and found that for the transfer of a pressure surface load to the nodal forces, depending on the element type (e.g. linear or quadratic), the corresponding force components should be taken into account, depending on whether it is a corner or midside node. 
This problem arises in particular with quadratic elements:
http://web.mit.edu/calculix_v2.7/CalculiX/ccx_2.7/doc/ccx/node147.html
As a possible solution for the use of pure node clouds in RBF mapping (where no connectivity information is available), it might be conceivable that the user creates several node sets, e.g. in CalculiX, with corresponding weighting information: E.g. one node set that contains all midside nodes and another that contains all corner nodes. Then, for example, in the case of quadratic tetrahedral elements, the initial calculated forces for the corner nodes could be redistributed to the midside nodes by preCICE according to a user-defined weighting factor of "0" for the corner node set.
For the displacements, it would then probably be necessary to work with the entire node set (corner and midside nodes) in order to obtain sufficient supporting points for the interpolated displacements. 
Ulrich

**Comment by IshaanDesai** [comment]
This issue was resolved via https://github.com/precice/calculix-adapter/pull/92
