### ISSUE TITLE
Redesigning of CalculiX adapter which allows ''STATIC" step for FSI simulation

### ISSUE THREAD

**Issue by rahuldevmeher** [precice/calculix-adapter#63]
Hello,

I want to do a steady-state FSI simulation using CalculiX as solid solver. Currently the CalculiX adapter only allows a “DYNAMIC” step for FSI. Whereas for doing a steady-state FSI, I need to use a “STATIC” step in CalculiX. If I use the keyword “**STATIC**” in CalculiX input file, the following error is shown in Solid.log - 
`**ERROR: Only thermal coupling or FSI is available with preCICE**`

So, what changes need to be made in the adapter to implement this new feature where the adapter allows a “STATIC” step as well ? Suggestions are requested to implement this feature.

**Comment by MatthiasFreimuth** [comment]
Hello,
I think the main changes would be:
1. Adapt the ccx_2.16.c file to enable further cases, where preCICE can be used here: https://github.com/precice/calculix-adapter/blob/9fefcef8ade330280cb300c25c78df6827b44684/ccx_2.16.c#L1109 
2. Adapt the linstatic.c routine to be able to interact with preCICE (include the preCICE-API in the main iteration/increment loop of the routine) Similar to a nonlingeo_precice.c there should then be a linstatic_precice.c
3. Include those changed files in the Makefiles accordingly
 
For my best knowledge that would be the general procedure to enable other simulation types of CalculiX for a preCICE simulation as well.

**Comment by IshaanDesai** [comment]
@MatthiasFreimuth thanks for your input!
@rahuldevmeher if you want, you can start modifying the adapter and also simultaneously open a draft pull request so that I can also see the changes and help with testing. You can then also assign yourself to this issue which would indicate to other users and developers that you are developing this feature.

**Comment by MatthiasFreimuth** [comment]
I just figured out there is a simpler way to enable Static steps for FSI simulations in the adapter. 
If one specifies the following in the CalculiX input file:

*STEP, NLGEOM
*STATIC
1,1
*END STEP

(so basically a STATIC step with the NLGEOM option, so that it is solved by the nonlingeo routine)
one does not need to adapt the linstatic.c routine and a small adaption of the ccx_2.16.c(or higher) file is enough.

**Comment by boris-martin** [comment]
So if I understand correctly (using adapter version from your PR):
- If you want to do a non-linear static analysis, you configure a STEP, NLGEOM with STATIC then define loads
- If you want to do a linear static analysis, you do the same and keep the keyword, just so we don't have to implement the adapter version of the linear static solver.

Am I right ?

**Comment by MatthiasFreimuth** [comment]
You're right. The NLGEOM option shouldn't change anything in the solution compared to the linear static case if there is physically no nonlinear behaviour.
